### ISSUE TITLE
Style changes

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#1]
### Description

Get the project started by hitting `npm i` followed by `npm start`.

Currently the project contains dummy data. I would appreciate if someone takes up the style part of it and enhance the project.

**Comment by Arnoldicus** [comment]
I can do that. Do you have some idea how it should look like?

**Comment by richardnikolas** [comment]
I could help you as well. But we need some kind of style guide, if you have one.

**Comment by manjeetaR** [comment]
> I can do that. Do you have some idea how it should look like?

I would say let your imagination fly. It can take any form. All the best.

**Comment by manjeetaR** [comment]
> I could help you as well. But we need some kind of style guide, if you have one.

Any third party library can also be used. Such as material-ui, antd. If you guys are familiar with that.

**Comment by Arnoldicus** [comment]
> > I can do that. Do you have some idea how it should look like?
> 
> I would say let your imagination fly. It can take any form. All the best.

Okay. I will do that :)

**Comment by Arnoldicus** [comment]
@manjeetaR just opened merge request, check this out > #2

**Comment by manjeetaR** [comment]
Great Work @Arnoldicus !!!
