### ISSUE TITLE
Editor component

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#11]
### Description

- An editor component which by default is bullet pointer and only that.

- Adds bullet on enter event.

**Comment by manAbl** [comment]
It's like a tag component for listing things right?

**Comment by manjeetaR** [comment]
> It's like a tag component for listing things right?

It would be an editorial, same as the comment session here. But only with bullet option. A third party library can be used.

**Comment by Luis-gd** [comment]
Can i take this issue?

**Comment by manjeetaR** [comment]
> Can i take this issue?

Sure, take it up.

**Comment by manjeetaR** [comment]
Resolved
