### ISSUE TITLE
Alert component styling

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#17]
### Description

- Style the alert component for both success and error statuses. 

- Keep it docked to the bottom of the page and rest can be experimented.

**Comment by JavaScriptErika** [comment]
Hello! I'd love to take on this issue!

**Comment by manjeetaR** [comment]
> Hello! I'd love to take on this issue!

Go for it.

**Comment by manjeetaR** [comment]
> Hello! I'd love to take on this issue!

Hi @JavaScriptErika , please do pull changes of master and resolved conflict as many PR where merged today.
