### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#18]
### Description

- Add a search bar and implement the functionality.

- On search filtered tasks should be shown.

**Comment by DevDigression** [comment]
Cool project! Happy to work on this one if no one has claimed it.

**Comment by manjeetaR** [comment]
> Cool project! Happy to work on this one if no one has claimed it.

Go for it.

**Comment by DevDigression** [comment]
PR: https://github.com/manjeetaR/Task-Manager/pull/24
