### ISSUE TITLE
Replace with informative icons 

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#22]
### Description

- Replace with informative icons where ever required.

**Comment by KaylaKremer** [comment]
Hi,
Can I take this one on?

**Comment by KaylaKremer** [comment]
PR: https://github.com/manjeetaR/Task-Manager/pull/27

**Comment by manjeetaR** [comment]
> PR: #27

Hi @KaylaKremer , please do pull changes of master and resolved conflict as many PR where merged today.
