### ISSUE TITLE
Dark mode/light mode

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#4]
### Description

The application needs a light/dark mode. Theme can be changed as required. Any sort of experiment is most welcomed.

**Comment by jessekoester** [comment]
Can I take this?

**Comment by manjeetaR** [comment]
> Can I take this?

Most Welcome.

**Comment by jessekoester** [comment]
Should have a PR out for this tomorrow!

**Comment by manjeetaR** [comment]
> Should have a PR out for this tomorrow!

Hi @jessekoester , please do pull changes of master and resolved conflict as many PR where merged today.

**Comment by jessekoester** [comment]
Even though a base dark light theme was pr'd please keep the issue open as I have a more robust dark theme that I am working on that will incorporate the work done above.

**Comment by manjeetaR** [comment]
> Even though a base dark light theme was pr'd please keep the issue open as I have a more robust dark theme that I am working on that will incorporate the work done above.

Sure @jessekoester

**Comment by manjeetaR** [comment]
Resolved
