### ISSUE TITLE
Redux store

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#5]
### Description

Currently dummy data is stored within the component. It needs to be shifted to redux store. Configure redux store, maintain constants, actions and reducers.

**Comment by miloskallai** [comment]
Hello, can I take this one?

**Comment by manjeetaR** [comment]
> Hello, can I take this one?

Most Welcome!

**Comment by miloskallai** [comment]
Do you want your redux state as it is in your app state?

**Comment by manjeetaR** [comment]
> Do you want your redux state as it is in your app state?

Yes that would be appropriate for coming features.

**Comment by miloskallai** [comment]
I created a new branch, but I can't push it, can you enable it?

**Comment by miloskallai** [comment]
and I accidentally removed my assignment...

**Comment by manjeetaR** [comment]
> I created a new branch, but I can't push it, can you enable it?

You ll have to fork the repo. Check documentation on contributing to open sources.

**Comment by miloskallai** [comment]
Thanks, I forget about that

**Comment by miloskallai** [comment]
I configured the basic redux, can you check it, if it is what you wanted? I still need some work to do with it (actually dispatch actions etc): https://github.com/miloskallai/Task-Manager

**Comment by manjeetaR** [comment]
> I configured the basic redux, can you check it, if it is what you wanted? I still need some work to do with it (actually dispatch actions etc): https://github.com/miloskallai/Task-Manager

Looks fine, go ahead with it.

**Comment by manjeetaR** [comment]
> I configured the basic redux, can you check it, if it is what you wanted? I still need some work to do with it (actually dispatch actions etc): https://github.com/miloskallai/Task-Manager

Hi @miloskallai , please do pull changes of master and resolved conflict as many PR where merged today.

**Comment by miloskallai** [comment]
@manjeetaR sorry, but it's too much change, I don't have time now to configure that scale in redux store, if you want to, you can use my basic configuration, I'll send you a PR, but it's ok to reject it
