### ISSUE TITLE
Alert component

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#6]
### Description

-An alert component that displays on each of the operations of add/delete/update. 

- Sticks at the bottom of the page.

- Prop is to be passed stating whether its for success or error.

**Comment by gabrieltrompiz** [comment]
Can I take this?

**Comment by manjeetaR** [comment]
> Can I take this?

Yes you may. All the best.

**Comment by manjeetaR** [comment]
@gabrieltrompiz Will be opening another issue for styling though. Great Work!!!
