### ISSUE TITLE
List card view

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#8]
### Description

- Each of the task should be shown as card list view.

- Add a edit icon on the card for it to back to it's edit mode.

**Comment by dishankmehta** [comment]
Can I work on this one?

**Comment by manjeetaR** [comment]
> Can I work on this one?

Yes go ahead. All the best.

**Comment by manjeetaR** [comment]
> Can I work on this one?

Hi @dishankmehta , please do pull changes of master and resolved conflict as many PR where merged today.

**Comment by dishankmehta** [comment]
Sure. I was going to work on this, this weekend so its fine anyways.

**Comment by dishankmehta** [comment]
Can you please elaborate on this? Don't we have the tasks as the cards list right now? And it is editable as of now.

**Comment by manjeetaR** [comment]
![image](https://user-images.githubusercontent.com/45707463/66715602-e280e280-ede2-11e9-87d4-3b30b27b824c.png)
A sample, on click of edit it should come to the view how it is now.

**Comment by manjeetaR** [comment]
Resolved
