### ISSUE TITLE
Add a timer

### ISSUE THREAD

**Issue by manjeetaR** [manjeetaR/Task-Manager#9]
### Description

- Add a timer against each task to show the time left.

- Timer should update every minute.

**Comment by vanya829** [comment]
@manjeetaR I want to get this one, but one have one question. 
What do you expect to see in this timer? 
![image](https://user-images.githubusercontent.com/1397979/66082783-8eb90280-e573-11e9-8860-ee8d4c0fd910.png)
I see that task manager allow use to set deadline date, but not time. So what time should we get, to calculate value for timer? 00:00:00 or 23:59:59 or something else. 
And it would be good to have preferable format.

**Comment by manjeetaR** [comment]
> @manjeetaR I want to get this one, but one have one question.
> What do you expect to see in this timer?
> ![image](https://user-images.githubusercontent.com/1397979/66082783-8eb90280-e573-11e9-8860-ee8d4c0fd910.png)
> I see that task manager allow use to set deadline date, but not time. So what time should we get, to calculate value for timer? 00:00:00 or 23:59:59 or something else.
> And it would be good to have preferable format.

It would be in the format of days hrs min (1d 13hrs 15min). As currently the field takes in only date and time field is not merged. It would just be days left. (1day)

**Comment by vanya829** [comment]
@manjeetaR Clear. Will implement it

**Comment by manjeetaR** [comment]
> @manjeetaR Clear. Will implement it

Sure. All the best.
